services:
  node-red:
    image: ghcr.io/mssaleh/node-red-docker:main
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      TZ: "Asia/Dubai"
      NODE_RED_ENABLE_PROJECTS: "True"
      # Replace these environment variable placeholders with your actual secret values,
      # or load them from a .env file or Docker secrets.
      NODE_RED_CREDENTIAL_SECRET: "${NODE_RED_CREDENTIAL_SECRET}"
      NODE_RED_ADMIN_USERNAME: "${NODE_RED_ADMIN_USERNAME}"
      NODE_RED_ADMIN_PASSWORD: "${NODE_RED_ADMIN_HASHED_PASSWORD}"
      NODE_RED_HTTP_USERNAME: "${NODE_RED_HTTP_USERNAME}"
      NODE_RED_HTTP_PASSWORD: "${NODE_RED_HTTP_HASHED_PASSWORD}"
    volumes:
      - ./nodered-data:/data
    user: "1000:1000"